// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calcpb/calc.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	SumResult            int32    `protobuf:"varint,1,opt,name=sum_result,json=sumResult,proto3" json:"sum_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

type PrimeNoDecompRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNoDecompRequest) Reset()         { *m = PrimeNoDecompRequest{} }
func (m *PrimeNoDecompRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNoDecompRequest) ProtoMessage()    {}
func (*PrimeNoDecompRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{2}
}

func (m *PrimeNoDecompRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNoDecompRequest.Unmarshal(m, b)
}
func (m *PrimeNoDecompRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNoDecompRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNoDecompRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNoDecompRequest.Merge(m, src)
}
func (m *PrimeNoDecompRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNoDecompRequest.Size(m)
}
func (m *PrimeNoDecompRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNoDecompRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNoDecompRequest proto.InternalMessageInfo

func (m *PrimeNoDecompRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNoDecompResponse struct {
	PrimeFactor          int64    `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor,proto3" json:"prime_factor,omitempty"`
	Power                int64    `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNoDecompResponse) Reset()         { *m = PrimeNoDecompResponse{} }
func (m *PrimeNoDecompResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNoDecompResponse) ProtoMessage()    {}
func (*PrimeNoDecompResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{3}
}

func (m *PrimeNoDecompResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNoDecompResponse.Unmarshal(m, b)
}
func (m *PrimeNoDecompResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNoDecompResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNoDecompResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNoDecompResponse.Merge(m, src)
}
func (m *PrimeNoDecompResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNoDecompResponse.Size(m)
}
func (m *PrimeNoDecompResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNoDecompResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNoDecompResponse proto.InternalMessageInfo

func (m *PrimeNoDecompResponse) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

func (m *PrimeNoDecompResponse) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type ComputeAverageRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageRequest) Reset()         { *m = ComputeAverageRequest{} }
func (m *ComputeAverageRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageRequest) ProtoMessage()    {}
func (*ComputeAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{4}
}

func (m *ComputeAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageRequest.Unmarshal(m, b)
}
func (m *ComputeAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageRequest.Marshal(b, m, deterministic)
}
func (m *ComputeAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageRequest.Merge(m, src)
}
func (m *ComputeAverageRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageRequest.Size(m)
}
func (m *ComputeAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageRequest proto.InternalMessageInfo

func (m *ComputeAverageRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ComputeAverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageResponse) Reset()         { *m = ComputeAverageResponse{} }
func (m *ComputeAverageResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageResponse) ProtoMessage()    {}
func (*ComputeAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{5}
}

func (m *ComputeAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageResponse.Unmarshal(m, b)
}
func (m *ComputeAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageResponse.Marshal(b, m, deterministic)
}
func (m *ComputeAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageResponse.Merge(m, src)
}
func (m *ComputeAverageResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageResponse.Size(m)
}
func (m *ComputeAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageResponse proto.InternalMessageInfo

func (m *ComputeAverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calc.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calc.SumResponse")
	proto.RegisterType((*PrimeNoDecompRequest)(nil), "calc.PrimeNoDecompRequest")
	proto.RegisterType((*PrimeNoDecompResponse)(nil), "calc.PrimeNoDecompResponse")
	proto.RegisterType((*ComputeAverageRequest)(nil), "calc.ComputeAverageRequest")
	proto.RegisterType((*ComputeAverageResponse)(nil), "calc.ComputeAverageResponse")
}

func init() { proto.RegisterFile("calcpb/calc.proto", fileDescriptor_a87762106ce7f1ca) }

var fileDescriptor_a87762106ce7f1ca = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x22, 0xa0, 0x03, 0x18, 0xd9, 0x00, 0x21, 0x55, 0x13, 0x59, 0x2f, 0x1c, 0x08, 0x18,
	0xfc, 0x05, 0x8a, 0xf1, 0x64, 0x90, 0x14, 0x4f, 0x5e, 0x48, 0x59, 0x17, 0x43, 0xd2, 0x65, 0xd7,
	0xfd, 0xc0, 0x7f, 0xea, 0xef, 0x31, 0xdd, 0x0f, 0x05, 0xd2, 0x53, 0x3b, 0x6f, 0xde, 0x7b, 0x7d,
	0x9d, 0x19, 0x68, 0x92, 0x34, 0x23, 0x62, 0x39, 0xca, 0x1f, 0x43, 0x21, 0xb9, 0xe6, 0xe8, 0x24,
	0x7f, 0xc7, 0x6f, 0x00, 0x73, 0xc3, 0x12, 0xfa, 0x65, 0xa8, 0xd2, 0xa8, 0x07, 0xf5, 0xd5, 0x5a,
	0x2a, 0xbd, 0xd8, 0x18, 0xb6, 0xa4, 0xb2, 0x1b, 0xdd, 0x44, 0xfd, 0x72, 0x52, 0xb3, 0xd8, 0xd4,
	0x42, 0xe8, 0x16, 0x1a, 0x8a, 0x12, 0xbe, 0xf9, 0x08, 0x9c, 0x63, 0xcb, 0xa9, 0x3b, 0xd0, 0x91,
	0xf0, 0x00, 0x6a, 0xd6, 0x55, 0x09, 0xbe, 0x51, 0x14, 0x5d, 0x03, 0x28, 0xc3, 0x16, 0x92, 0x2a,
	0x93, 0x69, 0x6f, 0x7a, 0xa6, 0x2c, 0xc1, 0x64, 0x1a, 0x0f, 0xa1, 0x35, 0x93, 0x6b, 0x46, 0xa7,
	0xfc, 0x89, 0x12, 0xce, 0x44, 0x48, 0xd3, 0x81, 0xca, 0x4e, 0x8e, 0x52, 0xe2, 0x2b, 0x3c, 0x83,
	0xf6, 0x01, 0xdf, 0x7f, 0xa7, 0x07, 0x75, 0x91, 0x37, 0x16, 0xab, 0x94, 0x68, 0x1e, 0x64, 0x35,
	0x8b, 0x3d, 0x5b, 0x08, 0xb5, 0xa0, 0x2c, 0xf8, 0xb7, 0x8f, 0x5d, 0x4a, 0x5c, 0x81, 0x47, 0xd0,
	0x9e, 0x70, 0x26, 0x8c, 0xa6, 0x0f, 0x5b, 0x2a, 0xd3, 0x4f, 0x5a, 0x1c, 0xa1, 0xfc, 0x17, 0x61,
	0x0c, 0x9d, 0x43, 0x81, 0xcf, 0xd0, 0x85, 0x6a, 0xea, 0x20, 0x2b, 0x89, 0x92, 0x50, 0x8e, 0x7f,
	0x22, 0xa8, 0x4e, 0xd2, 0x8c, 0xcc, 0xb7, 0x04, 0x0d, 0xa0, 0x34, 0x37, 0x0c, 0x5d, 0x0c, 0xed,
	0x42, 0xfe, 0x37, 0x10, 0x37, 0x77, 0x10, 0xe7, 0x88, 0x8f, 0xd0, 0x0b, 0x34, 0xf6, 0x7e, 0x18,
	0xc5, 0x8e, 0x55, 0x34, 0xb5, 0xf8, 0xb2, 0xb0, 0x17, 0xbc, 0xee, 0x22, 0xf4, 0x0a, 0xe7, 0xfb,
	0xd9, 0x91, 0x97, 0x14, 0x8e, 0x20, 0xbe, 0x2a, 0x6e, 0x06, 0xc3, 0x7e, 0xf4, 0x78, 0xfa, 0x5e,
	0x71, 0xe7, 0xb5, 0xac, 0xd8, 0xd3, 0xba, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x48, 0xe3,
	0xab, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalcSvcClient is the client API for CalcSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalcSvcClient interface {
	//Unary
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	//Stream Server
	PrimeNoDecomp(ctx context.Context, in *PrimeNoDecompRequest, opts ...grpc.CallOption) (CalcSvc_PrimeNoDecompClient, error)
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalcSvc_ComputeAverageClient, error)
}

type calcSvcClient struct {
	cc *grpc.ClientConn
}

func NewCalcSvcClient(cc *grpc.ClientConn) CalcSvcClient {
	return &calcSvcClient{cc}
}

func (c *calcSvcClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calc.CalcSvc/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcSvcClient) PrimeNoDecomp(ctx context.Context, in *PrimeNoDecompRequest, opts ...grpc.CallOption) (CalcSvc_PrimeNoDecompClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalcSvc_serviceDesc.Streams[0], "/calc.CalcSvc/PrimeNoDecomp", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcSvcPrimeNoDecompClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalcSvc_PrimeNoDecompClient interface {
	Recv() (*PrimeNoDecompResponse, error)
	grpc.ClientStream
}

type calcSvcPrimeNoDecompClient struct {
	grpc.ClientStream
}

func (x *calcSvcPrimeNoDecompClient) Recv() (*PrimeNoDecompResponse, error) {
	m := new(PrimeNoDecompResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calcSvcClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalcSvc_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalcSvc_serviceDesc.Streams[1], "/calc.CalcSvc/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcSvcComputeAverageClient{stream}
	return x, nil
}

type CalcSvc_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type calcSvcComputeAverageClient struct {
	grpc.ClientStream
}

func (x *calcSvcComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcSvcComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalcSvcServer is the server API for CalcSvc service.
type CalcSvcServer interface {
	//Unary
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	//Stream Server
	PrimeNoDecomp(*PrimeNoDecompRequest, CalcSvc_PrimeNoDecompServer) error
	ComputeAverage(CalcSvc_ComputeAverageServer) error
}

func RegisterCalcSvcServer(s *grpc.Server, srv CalcSvcServer) {
	s.RegisterService(&_CalcSvc_serviceDesc, srv)
}

func _CalcSvc_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcSvcServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.CalcSvc/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcSvcServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalcSvc_PrimeNoDecomp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNoDecompRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalcSvcServer).PrimeNoDecomp(m, &calcSvcPrimeNoDecompServer{stream})
}

type CalcSvc_PrimeNoDecompServer interface {
	Send(*PrimeNoDecompResponse) error
	grpc.ServerStream
}

type calcSvcPrimeNoDecompServer struct {
	grpc.ServerStream
}

func (x *calcSvcPrimeNoDecompServer) Send(m *PrimeNoDecompResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalcSvc_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcSvcServer).ComputeAverage(&calcSvcComputeAverageServer{stream})
}

type CalcSvc_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type calcSvcComputeAverageServer struct {
	grpc.ServerStream
}

func (x *calcSvcComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcSvcComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalcSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.CalcSvc",
	HandlerType: (*CalcSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalcSvc_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNoDecomp",
			Handler:       _CalcSvc_PrimeNoDecomp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalcSvc_ComputeAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calcpb/calc.proto",
}
